### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Aericio** [GMNetwork/GrabBag#1]
- [ ] Make this thing more easy to read (really)

- [ ] Add colors to messages, it looks ugly only white.

- [ ] Optimize code, as much as possible.
